import Head from 'next/head'

import Header from '../../components/Header/Header'
import Footer from '../../components/Footer/Footer'
import ListarUsuarios from '../../components/Usuario/ListarUsuario/Listar'
import UsuarioService from '../../service/Usuario.service'

export default function ListarUsuario({usuarios}) {
  return (
    <>
      <Head>
        <title>Listar | Discuss!t</title>
        <meta name="description" content="Generated by create next app" />  
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header hide={{ listar: true }} />

      <ListarUsuarios usuarios={usuarios}/>

      <Footer />
    </>
  )
}

export async function getServerSideProps(context) {
  const usuarios = await UsuarioService.getUsuarios()
  return {
    props: {
      usuarios
    }
  }
}