import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import bannerImage from '../public/bannerImage.png'
import Link from 'next/link'
import Header from '../components/Header/Header'
import Footer from '../components/Footer/Footer'

export default function HomePage() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home | Discuss!t</title>
        <meta name="description" content="Generated by create next app" />  
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header hide={ {home: true} }/>

      <main className={styles.main}>  
        <div className={styles.bannerText}>
          <span>Tecnologia | Esporte | Gastronomia | Política</span>
          <span>Seja o que for</span>
          <span>Mas </span><span>discuta!</span>
        </div>
        <Image src={bannerImage} alt="Conversation" width={860} height={860} layout='intrinsic'/>
      </main>

      <Footer />
    </div>
  )
}
